package gui;

import model.Retangulo;

/**
 *
 * @author brrimolo
 */
public class GuiRetangulo extends javax.swing.JFrame {

    /**
     * Creates new form GuiRetangulo
     */
    public GuiRetangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblX1 = new javax.swing.JLabel();
        txtFldX1 = new javax.swing.JTextField();
        lblY1 = new javax.swing.JLabel();
        txtFldY1 = new javax.swing.JTextField();
        lblX2 = new javax.swing.JLabel();
        txtFldX2 = new javax.swing.JTextField();
        lblY2 = new javax.swing.JLabel();
        txtFldY2 = new javax.swing.JTextField();
        lblX3 = new javax.swing.JLabel();
        txtFldX3 = new javax.swing.JTextField();
        lblY3 = new javax.swing.JLabel();
        txtFldY3 = new javax.swing.JTextField();
        txtFldRetangulo = new javax.swing.JTextField();
        btnCalcArea = new javax.swing.JButton();
        txtFldArea = new javax.swing.JTextField();
        btnCalcPerimetro = new javax.swing.JButton();
        txtFldPerimetro = new javax.swing.JTextField();
        lblX4 = new javax.swing.JLabel();
        txtFldX4 = new javax.swing.JTextField();
        lblY4 = new javax.swing.JLabel();
        txtFldY4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retângulo");

        lblX1.setText("X");

        txtFldX1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFldX1KeyReleased(evt);
            }
        });

        lblY1.setText("Y");

        txtFldY1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFldY1KeyReleased(evt);
            }
        });

        lblX2.setText("X");

        txtFldX2.setEditable(false);
        txtFldX2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldX2.setFocusable(false);

        lblY2.setText("Y");

        txtFldY2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFldY2KeyReleased(evt);
            }
        });

        lblX3.setText("X");

        txtFldX3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldX3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFldX3KeyReleased(evt);
            }
        });

        lblY3.setText("Y");

        txtFldY3.setEditable(false);
        txtFldY3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldY3.setFocusable(false);

        txtFldRetangulo.setEditable(false);
        txtFldRetangulo.setBackground(new java.awt.Color(51, 51, 51));
        txtFldRetangulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));
        txtFldRetangulo.setEnabled(false);
        txtFldRetangulo.setFocusable(false);

        btnCalcArea.setText("Calcular Área");
        btnCalcArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcAreaActionPerformed(evt);
            }
        });

        txtFldArea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnCalcPerimetro.setText("Calcular Perímetro");
        btnCalcPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcPerimetroActionPerformed(evt);
            }
        });

        txtFldPerimetro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblX4.setText("X");

        txtFldX4.setEditable(false);
        txtFldX4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldX4.setFocusable(false);

        lblY4.setText("Y");

        txtFldY4.setEditable(false);
        txtFldY4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFldY4.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblY1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldY1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblX2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldX2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblY2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldY2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblX1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldX1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblX3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldX3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblY3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldY3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblY4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldY4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblX4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFldX4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalcPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCalcArea, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(txtFldRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblX1)
                    .addComponent(txtFldX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblX4)
                    .addComponent(txtFldX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblY1)
                        .addComponent(txtFldY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFldY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblY4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFldRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblX2)
                    .addComponent(lblX3)
                    .addComponent(txtFldX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFldY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblY3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFldY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblY2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcArea)
                    .addComponent(txtFldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcPerimetro)
                    .addComponent(txtFldPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcAreaActionPerformed
        // TODO add your handling code here:
        Double x1 = Double.parseDouble(txtFldX1.getText());
        Double x2 = Double.parseDouble(txtFldX2.getText());
        Double x3 = Double.parseDouble(txtFldX3.getText());
        Double y1 = Double.parseDouble(txtFldY1.getText());
        Double y2 = Double.parseDouble(txtFldY2.getText());
        Double y3 = Double.parseDouble(txtFldY3.getText());
        
        Retangulo retangulo = new Retangulo(x3,y3,x2,y2,x2,y2,x1,y1);
        txtFldArea.setText(retangulo.getArea().toString());
    }//GEN-LAST:event_btnCalcAreaActionPerformed

    private void txtFldY2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFldY2KeyReleased
        // TODO add your handling code here:
        txtFldY3.setText(txtFldY2.getText());
    }//GEN-LAST:event_txtFldY2KeyReleased

    private void txtFldX1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFldX1KeyReleased
        // TODO add your handling code here:
        txtFldX2.setText(txtFldX1.getText());
    }//GEN-LAST:event_txtFldX1KeyReleased

    private void btnCalcPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcPerimetroActionPerformed
        // TODO add your handling code here:
        Double x1 = Double.parseDouble(txtFldX1.getText());
        Double x2 = Double.parseDouble(txtFldX2.getText());
        Double x3 = Double.parseDouble(txtFldX3.getText());
        Double y1 = Double.parseDouble(txtFldY1.getText());
        Double y2 = Double.parseDouble(txtFldY2.getText());
        Double y3 = Double.parseDouble(txtFldY3.getText());
        
        Retangulo retangulo = new Retangulo(x2,y2,x3,y3,x2,y2,x1,y1);
        txtFldPerimetro.setText(retangulo.getPerimetro().toString());
    }//GEN-LAST:event_btnCalcPerimetroActionPerformed

    private void txtFldX3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFldX3KeyReleased
        // TODO add your handling code here:
        txtFldX4.setText(txtFldX3.getText());
    }//GEN-LAST:event_txtFldX3KeyReleased

    private void txtFldY1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFldY1KeyReleased
        // TODO add your handling code here:
        txtFldY4.setText(txtFldY1.getText());
    }//GEN-LAST:event_txtFldY1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiRetangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiRetangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiRetangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiRetangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiRetangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcArea;
    private javax.swing.JButton btnCalcPerimetro;
    private javax.swing.JLabel lblX1;
    private javax.swing.JLabel lblX2;
    private javax.swing.JLabel lblX3;
    private javax.swing.JLabel lblX4;
    private javax.swing.JLabel lblY1;
    private javax.swing.JLabel lblY2;
    private javax.swing.JLabel lblY3;
    private javax.swing.JLabel lblY4;
    private javax.swing.JTextField txtFldArea;
    private javax.swing.JTextField txtFldPerimetro;
    private javax.swing.JTextField txtFldRetangulo;
    private javax.swing.JTextField txtFldX1;
    private javax.swing.JTextField txtFldX2;
    private javax.swing.JTextField txtFldX3;
    private javax.swing.JTextField txtFldX4;
    private javax.swing.JTextField txtFldY1;
    private javax.swing.JTextField txtFldY2;
    private javax.swing.JTextField txtFldY3;
    private javax.swing.JTextField txtFldY4;
    // End of variables declaration//GEN-END:variables
}
